2019-04-13 00:13:29,833 ERROR: Exception on /api/request/ [GET] [in /Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitrii/one_click/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dmitrii/one_click/app/api/helper.py", line 42, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/dmitrii/one_click/app/api/api.py", line 67, in request_all
    return json.dumps({'requests': Request.serialize_list(requests)}), 200, {'ContentType': 'application/json'}
  File "/Users/dmitrii/one_click/app/models.py", line 164, in serialize_list
    'user': m.user.name.serialize() if m.user is not None else None,
AttributeError: 'str' object has no attribute 'serialize'
2019-04-13 00:13:42,934 INFO: x5 startup [in /Users/dmitrii/one_click/app/__init__.py:61]
2019-04-13 09:47:28,056 INFO: x5 startup [in /Users/dmitrii/one_click/app/__init__.py:61]
2019-04-20 13:24:28,284 INFO: x5 startup [in /Users/dmitrii/one_click/app/__init__.py:61]
